apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ohv7i1n4c-go 
  janus-idp.io/tekton: ohv7i1n4c-go
  backstage.io/kubernetes-id: ohv7i1n4c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ohv7i1n4c-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  