apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ohv7i1n4c-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ohv7i1n4c-go 
  name: ohv7i1n4c-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ohv7i1n4c-go 
